# -*- coding: utf-8 -*-
"""ETL Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtV5sVyloAX3EfFHQ43FOyWwrINTHxYv

===============================================================================
Project: ETL Pipeline - Largest Banks by Market Capitalization

Author: Santiago Burgos

Language: Python 3
Description:
This project implements a complete ETL (Extract, Transform, Load) pipeline.
It extracts information about the world's largest banks from an archived
Wikipedia webpage, converts market capitalization values into multiple
currencies using exchange rates stored in a CSV file, stores the processed
data in CSV and SQLite formats, and executes SQL queries for validation.

Technologies:
- Python
- BeautifulSoup
- Requests
- Pandas
- SQLite3
- NumPy

===============================================================================
"""

# =============================================================================
# Import Required Libraries
# =============================================================================

import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3
import numpy as np
from datetime import datetime

# =============================================================================
# Global Variables
# Define source URLs, file paths, database names and table attributes.
# =============================================================================

URL='https://web.archive.org/web/20230908091635/https://en.wikipedia.org/wiki/List_of_largest_banks'
table_attribs = ["Name","MC_USD_Billion"]
table_attribs_final = ["Name", "MC_USD_Billion", "MC_GBP_Billion", "MC_EUR_Billion", "MC_INR_Billion"]
csv_path = 'exchange_rate.csv'
csv_output_path = "Largest_banks_data.csv"
db_name = 'Banks.db'
table_name = 'Largest_banks'
log_file = "code_log.txt"

# =============================================================================
# ETL FUNCTIONS
# =============================================================================

def extract(URL, table_attribs):
    """
    Extract bank information from an archived Wikipedia webpage.

    Parameters
    ----------
    URL : str
        URL of the archived Wikipedia page.

    table_attribs : list
        List containing the DataFrame column names.

    Returns
    -------
    pandas.DataFrame
        DataFrame containing the bank names and their market
        capitalization in USD.
    """
    response = requests.get(URL) # Send HTTP request to retrieve webpage content
    response.raise_for_status()
    html_page = response.text
    data = BeautifulSoup(html_page, 'html.parser') # Parse the HTML document using BeautifulSoup
    df = pd.DataFrame(columns=table_attribs)
    tables = data.find_all('tbody') # Locate the table containing bank information
    rows = tables[0].find_all('tr') # Iterate through each table row and extract the required columns
    for row in rows:
      col = row.find_all('td')
      if len(col) >= 3:
        name = col[1].find_all('a')
        if len(name) > 1:
          data_dict = {"Name": name[1].get_text(strip=True),"MC_USD_Billion": col[2].get_text(strip=True)}
          df1 = pd.DataFrame(data_dict, index=[0])
          df = pd.concat([df,df1], ignore_index=True)  # Append the extracted information to the DataFrame
    return df

def transform(df,csv_path):
    """
    Convert market capitalization values from USD into
    EUR, GBP and INR using exchange rates stored in a CSV file.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame containing bank information.

    csv_path : str
        Path to the exchange rate CSV file.

    Returns
    -------
    pandas.DataFrame
        Updated DataFrame containing additional currency columns.
    """
    csv_data = pd.read_csv(csv_path) # Read exchange rate data
    ex_rate = csv_data.set_index("Currency")["Rate"].to_dict() # Store exchange rates in a dictionary
    df["MC_USD_Billion"] = (
        df["MC_USD_Billion"]
        .str.replace(",", "", regex=False)
        .astype(float)
    )
    # Convert USD market capitalization into additional currencies
    df["MC_EUR_Billion"] = (
        df["MC_USD_Billion"] * ex_rate["EUR"]
    ).round(2)

    df["MC_GBP_Billion"] = (
        df["MC_USD_Billion"] * ex_rate["GBP"]
    ).round(2)

    df["MC_INR_Billion"] = (
        df["MC_USD_Billion"] * ex_rate["INR"]
    ).round(2)
    return df

def load_to_csv(df, csv_output_path):
    """
    Save the transformed DataFrame as a CSV file.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame to export.

    csv_output_path : str
        Destination CSV file path.
    """
    df.to_csv(csv_output_path, index = False)

def load_to_db(df, sql_connection, table_name):
    """
    Save the transformed DataFrame as a table in a SQLite database.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame to export.

    sql_connection : sqlite3.Connection
        SQLite database connection.
        table_name : str
        Name of the table to create.
    """
    df.to_sql(table_name, sql_connection, if_exists='replace', index=False)

def run_query(query_statement, sql_connection):
    """
    Execute a SQL query and print the output.

    Parameters
    ----------
    query_statement : str
        SQL query statement.

    sql_connection : sqlite3.Connection
        SQLite database connection.
    """
    query_output = pd.read_sql(query_statement, sql_connection)
    print("Query Statement: ","\n", query_statement)
    print("Query Output: ","\n", query_output)

def log_progress(message):
    """
    Log a progress message with a timestamp.

    Parameters
    ----------
    message : str
        Progress message to log.
    """
    timestamp_format = '%Y-%h-%d-%H:%M:%S'
    now = datetime.now()
    timestamp = now.strftime(timestamp_format)
    with open(log_file,"a") as f:
        f.write(timestamp + ',' + message + '\n')

# =============================================================================
# Main ETL Pipeline Execution
# =============================================================================

# Preliminaries complete. Initiating ETL process
log_progress("Preliminaries complete. Initiating ETL process.")

# Data extraction complete. Initiating Transformation process
log_progress("Data extraction complete. Initiating Transformation process")
df = extract(URL, table_attribs)
print("Extracted Data")
print(df)

# Data transformation complete. Initiating Loading process
log_progress("Data extraction complete. Initiating Transformation process.")
df = transform(df,csv_path)
print("Transformed Data")
print(df)

# Data saved to CSV file
log_progress("Data saved to CSV file")
load_to_csv(df, csv_output_path)

# SQL Connection initiated
log_progress("SQL Connection initiated.")
sql_connection = sqlite3.connect(db_name)
load_to_db(df, sql_connection, table_name)

#Data loaded to Database as a table, Executing queries
log_progress("Data loaded to Database as a table, Executing queries")
query_statement=f"SELECT * FROM Largest_banks"
run_query(query_statement, sql_connection)

query_statement=f"SELECT AVG(MC_GBP_Billion) FROM Largest_banks"
run_query(query_statement, sql_connection)

query_statement=f"SELECT name from Largest_banks LIMIT 5"
run_query(query_statement, sql_connection)

query_statement=f"SELECT Name, MC_USD_Billion FROM Largest_banks ORDER BY MC_USD_Billion DESC LIMIT 10;"
run_query(query_statement, sql_connection)

# Process Complete
log_progress("Process Complete")
sql_connection.close()
log_progress("Server Connection closed")